name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

concurrency:
  group: martinus-eshop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run BDD tests (HTML report)
        env:
          HEADLESS: 'true'
          BASE_URL: 'https://www.martinus.sk'
        run: npm run test:bdd:report

      - name: Upload test artifacts (HTML report + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            report.html
            playwright-report/**
            test-results/**
          retention-days: 7
